module IconsHelper
  # The icon of each document type listed in the documents dropdown
  DOCUMENT_ICONS = {
    'ai_summary' => :icon_description,
    'transcription' => :icon_speech_to_text,
    'shared_notes' => :icon_shared_notes,
    'engagement_report' => :icon_learning_dashboard,
    'participants_list' => :icon_groups,
    'recording' => :icon_recording_documents
  }.freeze

  def icon_visibility(options={})
    material_icon_constructor "visibility", "icon material-icons icon-visibility", options
  end

  def icon_visibility_off(options={})
    material_icon_constructor "visibility_off", "icon material-icons icon-visibility-off", options
  end

  def icon_deleted(options={})
    material_icon_constructor "delete_forever", "icon material-icons icon-deleted", options
  end

  def icon_file_download(options={})
    material_icon_constructor "file_download", "icon material-icons icon-file-download", options
  end

  def icon_conference_play(options={})
    material_icon_constructor "play_arrow", "icon material-icons icon-conference-play", options
  end

  def icon_recording_load(options={})
    material_icon_constructor "hourglass_top", "icon material-icons icon-recording-load", options
  end

  def icon_options_dots(options={})
    material_icon_constructor "more_vert", "icon material-icons icon icon-options-dots", options
  end

  def icon_ai_summary(options={})
    image_tag 'icon-ai-summary.svg'
  end

  def icon_ai_artifacts_elos(options={})
    image_tag 'icon_ai_artifacts_elos.svg', options
  end
  
  def icon_ai_artifacts_rnp(options={})
    image_tag 'icon_ai_artifacts_rnp.svg', options
  end

  def icon_dropdown_arrow(options={})
    image_tag("icon-dropdown.svg", class: "icon-dropdown")
  end

  def icon_content_copy(options={})
    image_tag 'content_copy.svg'
  end

  def icon_hide_recording(options={})
    image_tag 'hide_recording.svg', options
  end

  def icon_show_recording(options={})
    image_tag 'visibility.svg', options
  end

  def icon_learning_dashboard(options={})
    material_icon_constructor "chart_data", "icon material-symbols-rounded icon-chart-data", options
  end

  def icon_delete(options={})
    image_tag 'delete.svg'
  end

  def icon_download(options={})
    material_icon_constructor "download", "icon material-symbols-rounded icon-download", options
  end

  def icon_description(options={})
    material_icon_constructor "description", "icon material-symbols-rounded icon-description", options
  end

  def icon_speech_to_text(options={})
    material_icon_constructor "speech_to_text", "icon material-symbols-rounded icon-speech-to-text", options
  end

  def icon_progress_activity(options={})
    material_icon_constructor "progress_activity", "icon material-symbols-rounded icon-progress-activity", options
  end

  def icon_groups(options={})
    material_icon_constructor "groups", "icon material-symbols-rounded icon-groups", options
  end

  def icon_analytics(options={})
    material_icon_constructor "analytics", "icon material-icons icon-analytics", options
  end

  def icon_arrow_right(options={})
    material_icon_constructor "chevron_right", "icon material-icons icon-chevron-right", options
  end

  def icon_video_library(options={})
    material_icon_constructor "video_library", "icon material-symbols-rounded icon-video-library", options
  end

  def icon_filesender(options={})
    image_tag 'icon_filesender.svg'
  end

  def icon_eduplay(options={})
    image_tag 'icon_eduplay.svg'
  end

  def icon_plus(options={})
    material_icon_constructor "add", "icon material-symbols-rounded icon-plus", options
  end

  def icon_info_circle(options={})
    material_icon_constructor "info", "icon material-symbols-rounded icon icon-info", options
  end

  def icon_not_check(options={})
    material_icon_constructor "close", "icon material-symbols-rounded icon-not-check", options
  end

  def icon_upload_image(options={})
    material_icon_constructor "image_arrow_up", "icon material-symbols-rounded icon-upload-image", options
  end

  def icon_text_documents(options={})
    material_icon_constructor "description", "icon material-symbols-rounded icon-text-documents", options
  end

  def icon_recording_documents(options={})
    material_icon_constructor "radio_button_checked", "icon material-symbols-rounded icon-recording-documents", options
  end

  def icon_shared_notes(options={})
    material_icon_constructor "sticky_note_2", "icon material-symbols-rounded icon-shared-notes", options
  end

  # Shown on a document row that has no file to offer
  def icon_document_unavailable(options={})
    material_icon_constructor "error", "icon material-symbols-rounded icon-document-unavailable", options
  end

  # Marks a document as generated by AI, shown next to its label
  def icon_ai_generated(options={})
    material_icon_constructor "auto_awesome", "icon material-symbols-rounded icon-ai-generated", options
  end

  def document_icon(type, options={})
    helper = DOCUMENT_ICONS[type.to_s]
    return if helper.nil?

    send(helper, options)
  end

  # Base method for most of the methods above
  def icon_constructor(title=nil, cls=nil, options={})
    options[:class] = options.has_key?(:class) ? cls + " " + options[:class] : cls
    title = title.nil? ? options[:title] : title
    unless title.nil? or title.blank?
      options = options_for_tooltip(title, options)
    end
    content_tag :i, nil, options
  end

  def material_icon_constructor(icon=nil, cls=nil, options={})
    options[:class] = options.has_key?(:class) ? cls + " " + options[:class] : cls
    title = title.nil? ? options[:title] : title
    unless title.nil? or title.blank?
      options = options_for_tooltip(title, options)
    end
    content_tag :i, icon, options
  end

  def text_icon_constructor(title, cls=nil, text=nil, options={})
    options[:class] = options.has_key?(:class) ? cls + options[:class] : cls
    content_tag :span, text, options_for_tooltip(title, options)
  end
end
