#!/bin/bash -x

ADDITIONAL_THEMES=("rnp" "coc")
for THEME in "${ADDITIONAL_THEMES[@]}"; do
  docker build -t $IMAGE_NAME-${THEME} --build-arg APP_THEME=${THEME} -f $DOCKERFILE_PATH .
  docker push $IMAGE_NAME-${THEME}
done

docker build -t $IMAGE_NAME --build-arg APP_THEME="elos" -f $DOCKERFILE_PATH .

