---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mconf-lti-broker
  namespace: app-lti
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  selector:
    matchLabels:
      app: mconf-lti-broker
  template:
    metadata:
      labels:
        app: mconf-lti-broker
        revision: "1"
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: mconf-lti-broker
          image: mconf/bbb-lti-broker:v0.3.0-elos
          imagePullPolicy: Always
          # To test with local image (docker build -t bbb-lti-broker-local .)
          # image: bbb-lti-broker-local
          # imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mconf-lti-broker-cm
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mconf-lti-broker-secret
                  key: DATABASE_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mconf-lti-broker-secret
                  key: SECRET_KEY_BASE
            - name: OMNIAUTH_BBBLTIBROKER_KEY
              valueFrom:
                secretKeyRef:
                  name: mconf-lti-broker-secret
                  key: OMNIAUTH_BBBLTIBROKER_KEY
            - name: OMNIAUTH_BBBLTIBROKER_SECRET
              valueFrom:
                secretKeyRef:
                  name: mconf-lti-broker-secret
                  key: OMNIAUTH_BBBLTIBROKER_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 600m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /lti/healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /lti/healthz
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/db/seeds.rb
            subPath: seeds.rb
          - name: config-volume
            mountPath: /usr/src/app/scripts/start.sh
            subPath: start.sh
      volumes:
        - name: config-volume
          configMap:
            name: mconf-lti-broker-scripts-cm
            defaultMode: 0777
