---
apiVersion: v1
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQDE5Mi4xNjguMC42OjU0MzMvbHRpX3Jvb21zCg=="
  SECRET_KEY_BASE: "cGFzc3dvcmQK"
kind: Secret
metadata:
  name: mconf-lti-rooms-secret
  namespace: app-lti
type: Opaque
