---
apiVersion: v1
kind: Service
metadata:
  name: mconf-lti-rooms-svc
  namespace: app-lti
spec:
  type: ClusterIP
  selector:
    app: mconf-lti-rooms
  ports:
    - port: 3000
      targetPort: 3000
